//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealsNZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int CardId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CardNumber { get; set; }
        public Nullable<int> CardExpiryMonth { get; set; }
        public Nullable<int> CardExpiryYear { get; set; }
        public string CardHolderName { get; set; }
        public string CardType { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
