//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealsNZ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Coupon
    {
        public int CouponId { get; set; }
        [DisplayName("Coupon")]
        public string CouponUniqueText { get; set; }
        [DisplayName("Expiry")]
        public Nullable<System.DateTime> CouponValidTill { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DealId { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        [DisplayName("No.of Coupon")]
        public Nullable<int> CouponQty { get; set; }
        [DisplayName("Reedemfor")]
        public Nullable<int> ReedemNo { get; set; }
    
        public virtual Deal Deal { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
