//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealsNZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.Deals = new HashSet<Deal>();
        }
    
        public int StoreId { get; set; }
        public string StoreName { get; set; }
        public Nullable<int> StoreAddress { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Contact { get; set; }
        public string IdentificationImage { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal> Deals { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
