//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealsNZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVerification
    {
        public int UserVerificationID { get; set; }
        public System.Guid UserVerificationCode { get; set; }
        public int Userid { get; set; }
        public string Purpose { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
