//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealsNZ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        public int WalletId { get; set; }
        public Nullable<decimal> WalletCredit { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> WalletCreditDate { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
